workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set iOS deployment target to 13.0
        script: |
          echo "Patching iOS deployment target to 13.0"
          sed -i '' 's/platform :ios, *[\'"][0-9.]\\+[\'"]/platform :ios, '\''13.0'\''/' ios/Podfile || echo "No Podfile yet"
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release
      - name: Build Android app
        script: |
          flutter build apk --release
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/app/outputs/flutter-apk/app-release.apk
