name: khushhali_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  fluttertoast: ^8.2.8
  firebase_storage: ^12.3.1
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.1
  emailjs: ^4.0.0
  intl: ^0.19.0
  share_plus: ^10.1.1
  shared_preferences: ^2.3.2
  flutter_localizations:
    sdk: flutter
  video_player: ^2.9.2
  carousel_slider: ^5.0.0
  connectivity_plus: ^4.0.1
  cloud_functions: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#3532cb"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: assets/splash_screen.png
  android: true
  ios: true
  web: false
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/default_avatar.png
    - assets/icon/icon.png
    - assets/background.png
    - assets/splash_screen.png
    - assets/graph_icon.png
